name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Use the latest available version

      - name: Install Node.js
        uses: actions/setup-node@v2 # Use the latest available version
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress\e2e\tests\verifysecond.cy.js

      - name: Upload Cypress test results
        uses: cypress-io/github-action@v6
        with:
          enableDashboardUpload: true

