name: Cypress Tests

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install  # or yarn install if you use Yarn

      - name: Run Cypress tests
        run: npm run cypress\e2e\tests\verifysecond.cy.js
    

      - name: Upload Cypress test results
        uses: cypress-io/github-action@v6
        with:
          enableDashboardUpload: true
