name: Continuous 

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/e2e/tests






         
