name: Continuous Integration with Cypress Tests

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/e2e/tests






         
